### ISSUE TITLE
请问python对于VPN调用问题

### ISSUE THREAD

**Issue by RuiKylin** [luyishisi/Anti-Anti-Spider#19]
写爬虫的时候发现代理可以用http，socks等之类的，那假如要用VPN的话是怎样的
不知道具体的做法，搜索无果，自己用的时候是手动切换Orz，求给个思路

**Comment by cryzlasm** [comment]
VPN就是拨号额, 查一下拨号相关  不行调用API呗

**Comment by RuiKylin** [comment]
可以，用dbus来调用，查了一下，的确行，谢谢
