### ISSUE TITLE
猫眼电影票使用了字体处理票房数据，这种怎么抓取

### ISSUE THREAD

**Issue by walker02** [luyishisi/Anti-Anti-Spider#5]
https://piaofang.maoyan.com

猫眼电影的票房和评分数据使用的是特殊字体处理的，这种一般怎么爬取

**Comment by luyishisi** [comment]
你开f12.他的信息是没几秒钟请求一次抓取的，，你直接取他后台的json数据，我看了下，基本都有

**Comment by luyishisi** [comment]
![image](https://cloud.githubusercontent.com/assets/13358272/24795161/ecc79524-1bba-11e7-899d-b42ce6c4445e.png)
