### ISSUE TITLE
代理有没有一个统一的解决方案？

### ISSUE THREAD

**Issue by mengguiyouziyi** [luyishisi/Anti-Anti-Spider#6]
感觉文件分类和文件名字还有解释有点乱，注释和文档能详尽一点么？非常感谢！

**Comment by luyishisi** [comment]
sorry。不好意思，这部分代码是一路学习时留下的项目文件，现在风格并不统一，如果有疑问的具体请联系我。或者从博文中查看

**Comment by malone6** [comment]
第7点，ip伪造可以具体说下吗

**Comment by luyishisi** [comment]
请求头中有一个x-forword-for，他的意思是你的请求经过了哪些透明代理。部分网站，对你的封ip策略是针对你的代理的，那么就是伪造这个字段即可，你可以通过访问：https://httpbin.org/get?show_env=1 来看看自己的请求头。通过安装一个chrome插件 ：Modify Headers for Google Chrome 来进行伪造测试。
